# Generated by Django 5.2.4 on 2025-08-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
